# Generated by Django 3.1.2 on 2020-10-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_id', models.IntegerField()),
                ('smiles', models.CharField(max_length=100)),
                ('molecular_weight', models.FloatField()),
                ('a_log_p', models.FloatField()),
                ('num_rings', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('target', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
                ('operator', models.CharField(max_length=3)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.compound')),
            ],
        ),
    ]
