# Generated by Django 3.1.2 on 2020-10-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('compound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('smiles', models.CharField(max_length=100)),
                ('molecular_weight', models.DecimalField(decimal_places=5, max_digits=10)),
                ('a_log_p', models.DecimalField(decimal_places=3, max_digits=10)),
                ('molecular_formula', models.CharField(max_length=50)),
                ('num_rings', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=10)),
                ('operator', models.CharField(max_length=3)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assay_results', to='compounds.compound')),
            ],
        ),
    ]
