# Generated by Django 3.1.2 on 2020-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_compound_molecular_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='a_log_p',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
